version: '3'

services: 
  app:
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - .:/app
      #- /app/node_modules
    restart: on-failure 
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"